### ISSUE TITLE
Add tag to current version

### ISSUE THREAD

**Issue by AlFontal** [atmos-python/atmos#18]
Hi!

As it stands the last tagged version of `atmos` is 0.2.5, which corresponds to a version that fails when trying to install via pip > 10.0.
My last PR fixed the issue with the import of `pip.req`, but the only way to successfully circumvent the issue as of now is to specify the develop branch and installing directly from github:
```
pip install --git git@github.com:atmos-python/atmos.git@develop
```

or if using a wrapper like poetry:

```
poetry add --git git@github.com:atmos-python/atmos.git@develop
```
It works, but it's quite cumbersome and will probably frustrate users not aware of the issue.

Could you add a tag to the current version so that it gets its own wheel in Pypi and the default installation falls back to the current version?

Thanks!

**Comment by AlFontal** [comment]
I see that your current `fix/setup` also fixes this in a cleaner, way, so just tagging any of these working versions should ease the whole thing! :smile:

**Comment by mcgibbon** [comment]
Yes, this package could use some TLC! Tagging isn't enough here, since I never set up automatic releases for this repo.

I just merged the pip install fixes to master and did a manual `v0.2.6` release. Please let me know if anything's still broken.

**Comment by AlFontal** [comment]
Oh, great! `v0.2.6` release seems to be working now.

**Comment by mcgibbon** [comment]
Great! Thanks for the ping. Let me know if you run into other issues.
