### ISSUE TITLE
Installation on Debian 12 Bookworm

### ISSUE THREAD

**Issue by gnsbglora** [atmos-python/atmos#19]
after a successful installation on Debian bookworm with pip3 install atmos --break-system-packages
the command python3 -c "import atmos"  produces the error message 

traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/dist-packages/atmos/__init__.py", line 24, in <module>
    from atmos.solve import calculate, FluidSolver
  File "/usr/local/lib/python3.11/dist-packages/atmos/solve.py", line 8, in <module>
    from atmos import equations
  File "/usr/local/lib/python3.11/dist-packages/atmos/equations.py", line 301, in <module>
    @autodoc(equation=r'AH = q_v \rho')
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/atmos/decorators.py", line 73, in decorator
    in_quantities = inspect.getargspec(func).args
                    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

The python version is 3.11.2 , atmos is 0.2.6

**Comment by mcgibbon** [comment]
Apparently the python builtin library ‘inspect’ has changed and broken the package. I no longer actively maintain this package, and don’t have a fix for you. You could reference the equations.py file and copy paste out the equations you need for your use case, if that works, or you could try a downgraded python version.

If you update the package itself, feel free to open a PR.

**Comment by gnsbglora** [comment]
To close this, I used the equations.py file to create a function:

```
def absolute_humidity(relative_humidity, barometric_pressure, temperature):
   # Convert relative humidity to a fraction.
   relative_humidity_fraction = relative_humidity / 100
   # Calculate the saturation vapor pressure in Pa.
   saturation_vapor_pressure = 610.78 * np.exp(17.27 * temperature / (temperature + 237.3))
   # Calculate the absolute humidity in g/m³.
   absolute_humidity = saturation_vapor_pressure * relative_humidity_fraction * (1 / barometric_pressure) * 1000
   return absolute_humidity
```
