### ISSUE TITLE
Which version of atmos support moisture?

### ISSUE THREAD

**Issue by SC-PIONEER** [atmos-python/atmos#20]
**Hello. 

While I was running some codes from NASA, I found some atmos installation version errors.** 
 
=========================
```
# loading the NEWT package - we'll use this later for calculating Tw
from atmos import moisture
from atmos import thermo
```
===========================
I have used Ubuntu 22.04.03 env. 
A python version was 3.8. 
 
**When I ran above codes, I have faced below errors. 
Would you let me know which version should I install to correct this error?** 

===========================
```
ImportError                               Traceback (most recent call last)
[<ipython-input-10-f54748f36a9a>](https://localhost:8080/#) in <cell line: 2>()
      1 # loading the NEWT package - we'll use this later for calculating Tw
----> 2 from atmos import moisture
      3 from atmos import thermo

ImportError: cannot import name 'moisture' from 'atmos' (/usr/local/lib/python3.10/dist-packages/atmos/__init__.py)
```

==============================

Thank you for reading this.
hope to listening good solutions. 

JH lee

**Comment by mcgibbon** [comment]
I suspect you are looking for a different package called atmos, as this is not related to anything called NEWT or to NASA. The package has never had those symbols.

You’ll need to uninstall this package and install the correct one, whatever it is.

**Comment by mcgibbon** [comment]
This is probably the package you're looking for: https://github.com/robwarrenwx/atmos

**Comment by SC-PIONEER** [comment]
Thank you mcgibbon ! 

I have resolved this issue by using your recommended package. 
Thank you for your help. 

:)  Best regards. 

Jiheon Lee
