### ISSUE TITLE
Adiabatic lapse rate too low

### ISSUE THREAD

**Issue by am-thyst** [atmos-python/atmos#6]
Using:

`rvs = atmos.equations.rvs_from_qvs(qvs)
`
`lr = atmos.equations.Gammam_from_rvs_T(rvs, T)
`
Gives very low values for lr (adiabatic lapse rate). Temperature is definitely in K, QVS is definitely in kg/kg. Below is a plot I made just to visualise the data, with lapse rate on the x axis and temperature on the y axis. Was calculated and plotted for a higher pressure level too, which also seemed to max out at 0.010 LR. Am I doing something wrong, or just missing something?

![image](https://user-images.githubusercontent.com/41115380/42624379-2710986c-85bd-11e8-910c-34d49151fafa.png)

Edit: found a simple work around, not using atmos, but it would still be interesting to know what's happening here.

**Comment by mcgibbon** [comment]
Lapse rate is in degK per m. If the far right of the plot corresponds to low rvs then this should be pretty accurate.

**Comment by am-thyst** [comment]
@mcgibbon thank you! Should've checked that
